services:
  angular-gifs:
    image: nruz176/angular-gifs-app
    restart: always
    ports:
      - "4200:80"   # Asegúrate de que el puerto 80 esté expuesto
    container_name: angular-gifs
    networks:
      - angular-net

networks:
  angular-net:
    driver: bridge
